import "reflect-metadata";
import "@mantine/core/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import { TanstackProvider } from "@/components/TanstackProvider";
import { AuthProvider } from "@/context-provider/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <TanstackProvider>
          <AuthProvider>
            <MantineProvider>{children}</MantineProvider>
          </AuthProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
